-- Сначала создаем таблицы, на которые будут ссылаться другие
CREATE TABLE IF NOT EXISTS genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    login VARCHAR(200) NOT NULL CHECK (login <> ''),
    name VARCHAR(200),
    birthday DATE CHECK (birthday <= CURRENT_DATE)
);

CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS directors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200)
);

-- Затем создаем таблицы с внешними ключами
CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL CHECK (name <> ''),
    description VARCHAR(200),
    release_date DATE, -- CHECK (release_date <= CURRENT_DATE), -- требуют тесты ветки add-director
    duration INT CHECK (duration > 0),
    mpa BIGINT REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS friends (
    sender_id BIGINT REFERENCES users(id),
    receiver_id BIGINT REFERENCES users(id),
    
    PRIMARY KEY (sender_id, receiver_id),
    CONSTRAINT friends_check CHECK (sender_id <> receiver_id)
);

CREATE TABLE IF NOT EXISTS films_likes (
    film_id BIGINT REFERENCES films(id),
    user_id BIGINT REFERENCES users(id),
    
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS films_genres (
    film_id BIGINT REFERENCES films(id),
    genre_id BIGINT REFERENCES genre(id),
    
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS films_directors (
    film_id BIGINT REFERENCES films(id),
    director_id BIGINT REFERENCES directors(id),
    
    PRIMARY KEY (film_id, director_id)
);

-- Таблица отзывов
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id BIGINT REFERENCES films(id),
    user_id BIGINT REFERENCES users(id),
    content TEXT NOT NULL,
    is_positive BOOLEAN NOT NULL
);

-- Таблица лайков/дизлайков отзывов
CREATE TABLE IF NOT EXISTS reviews_likes (
    review_id BIGINT REFERENCES reviews(id),
    user_id BIGINT REFERENCES users(id),
    is_useful BOOLEAN,
    
    PRIMARY KEY (review_id, user_id)
);